repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.11.3  # Must be the same as in pyproject.toml.
    hooks:
      - id: isort
        files: '^(git_loc|tests)/'
        types: [file, python]
  - repo: https://github.com/python/black
    rev: 22.12.0  # Must be the same as in pyproject.toml.
    hooks:
      - id: black
        language_version: python3.11
        files: '^(git_loc|tests)/'
        types: [file, python]
