# Secrets are stored in:
# - PRODUCTION: environment variables.
# - DEVELOPMENT and TEST: in `./conf/secrets.toml` which is git-ignored (copy the example
#    from `./conf/secrets.EXAMPLE.toml`)
#
# Note: anything defined here overrides default settings.
# To be used mainly for secrets, but also for any specific settings a developer
# might want to override in the local env only.

[default]


[test]

